FROM python:3.10-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
COPY requirements.txt .
RUN uv pip install --system --no-cache --index-strategy unsafe-best-match -r requirements.txt

# Copy frontend files
COPY ui/ ./ui/

# Expose port
EXPOSE 8501

ENV PYTHONPATH=/app

ENV HOST=0.0.0.0
ENV PORT=8501

CMD ["chainlit", "run", "ui/app.py", "--host", "0.0.0.0", "--port", "8501", "--headless"]
